/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const sidebar: string;
const wrapper: string;
const logo: string;

export {
	sidebar,
	wrapper,
	logo
};

export default {
	sidebar,
	wrapper,
	logo
}
