/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const sidebarLink: string;
const active: string;
const wrapper: string;
const logo: string;
const logoWrapper: string;

export {
	sidebarLink,
	active,
	wrapper,
	logo,
	logoWrapper
};

export default {
	sidebarLink,
	active,
	wrapper,
	logo,
	logoWrapper
}
