/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const sidebar: string;
const a: string;
const wrapper: string;
const logo: string;
const logoWrapper: string;
const hr: string;

export {
	sidebar,
	a,
	wrapper,
	logo,
	logoWrapper,
	hr
};

export default {
	sidebar,
	a,
	wrapper,
	logo,
	logoWrapper,
	hr
}
