/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const searchBar: string;
const searchBarWrapper: string;
const filtersWrapper: string;

export {
	searchBar,
	searchBarWrapper,
	filtersWrapper
};

export default {
	searchBar,
	searchBarWrapper,
	filtersWrapper
}
