/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const searchBar: string;
const searchBarWrapper: string;
const filtersWrapper: string;
const yesNoButtonsWrapper: string;
const yesNoButton: string;
const onboardedWrapper: string;
const verticalLine: string;
const select: string;

export {
	searchBar,
	searchBarWrapper,
	filtersWrapper,
	yesNoButtonsWrapper,
	yesNoButton,
	onboardedWrapper,
	verticalLine,
	select
};

export default {
	searchBar,
	searchBarWrapper,
	filtersWrapper,
	yesNoButtonsWrapper,
	yesNoButton,
	onboardedWrapper,
	verticalLine,
	select
}
