/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const searchBarWrapper: string;
const searchBar: string;
const searchAddWrapper: string;

export {
	searchBarWrapper,
	searchBar,
	searchAddWrapper
};

export default {
	searchBarWrapper,
	searchBar,
	searchAddWrapper
}
