/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const tableWrapper: string;
const theadWrapper: string;
const tbodyWrapper: string;

export {
	tableWrapper,
	theadWrapper,
	tbodyWrapper
};

export default {
	tableWrapper,
	theadWrapper,
	tbodyWrapper
}
