/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const pairWrapper: string;
const team: string;
const teamInputs: string;
const logoPWrapper: string;
const p: string;
const logoAndNameWrapper: string;
const companyLogoP: string;
const buttonToggle: string;
const toggleDomainOff: string;
const toggleDomainOn: string;
const textarea: string;

export {
	pairWrapper,
	team,
	teamInputs,
	logoPWrapper,
	p,
	logoAndNameWrapper,
	companyLogoP,
	buttonToggle,
	toggleDomainOff,
	toggleDomainOn,
	textarea
};

export default {
	pairWrapper,
	team,
	teamInputs,
	logoPWrapper,
	p,
	logoAndNameWrapper,
	companyLogoP,
	buttonToggle,
	toggleDomainOff,
	toggleDomainOn,
	textarea
}
