/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const mainContent: string;
const pairWrapper: string;
const logoPWrapper: string;
const p: string;
const logoAndNameWrapper: string;
const companyLogoP: string;
const buttonToggle: string;
const toggleDomainOff: string;
const toggleDomainOn: string;
const textarea: string;
const cardAlignment: string;
const cancelButton: string;
const saveButtonWrapper: string;
const saveButton: string;
const saveButtonText: string;
const domainLabel: string;

export {
	mainContent,
	pairWrapper,
	logoPWrapper,
	p,
	logoAndNameWrapper,
	companyLogoP,
	buttonToggle,
	toggleDomainOff,
	toggleDomainOn,
	textarea,
	cardAlignment,
	cancelButton,
	saveButtonWrapper,
	saveButton,
	saveButtonText,
	domainLabel
};

export default {
	mainContent,
	pairWrapper,
	logoPWrapper,
	p,
	logoAndNameWrapper,
	companyLogoP,
	buttonToggle,
	toggleDomainOff,
	toggleDomainOn,
	textarea,
	cardAlignment,
	cancelButton,
	saveButtonWrapper,
	saveButton,
	saveButtonText,
	domainLabel
}
