/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const logoPWrapper: string;
const companyLogoP: string;
const p: string;

export {
	logoPWrapper,
	companyLogoP,
	p
};

export default {
	logoPWrapper,
	companyLogoP,
	p
}
