/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const logoPWrapper: string;
const className: string;

export {
	logoPWrapper,
	className
};

export default {
	logoPWrapper,
	className
}
