/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const logoPlaceholder: string;

export {
	logoPlaceholder
};

export default {
	logoPlaceholder
}
