/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const topBarWrapper: string;
const searchBarWrapper: string;
const input: string;
const img: string;

export {
	topBarWrapper,
	searchBarWrapper,
	input,
	img
};

export default {
	topBarWrapper,
	searchBarWrapper,
	input,
	img
}
