/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const topBarWrapper: string;
const searchBarWrapper: string;
const input: string;
const img: string;
const pWrapper: string;
const logoPWrapper: string;

export {
	topBarWrapper,
	searchBarWrapper,
	input,
	img,
	pWrapper,
	logoPWrapper
};

export default {
	topBarWrapper,
	searchBarWrapper,
	input,
	img,
	pWrapper,
	logoPWrapper
}
