/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const theme: string;
const fontFamily: string;
const h3: string;

export {
	theme,
	fontFamily,
	h3
};

export default {
	theme,
	fontFamily,
	h3
}
